# SPDX-FileCopyrightText: The Calyx Institute
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [".gitreview"]
precedence = "override"
SPDX-FileCopyrightText = "The Calyx Institute"
SPDX-License-Identifier = "Apache-2.0"
